Models/ErrorViewModel.cs
namespace progra.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace progra.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registrar(Contacto contacto)
        {
            double igv;
            if(contacto.Membresia=="Básico"){
                igv=500*0.18;
            }else{
                igv=1000*0.18;
            }
            ViewData["MsgRpta"] = $"Gracias por su inscripción en {contacto.Membresia} el IGV sería {igv}";
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }

    public class Contacto
    {
         public string? Nombre { get; set; }
        public int? Edad { get; set; }
        public string? Genero { get; set; }
        public string? Fecha { get; set; }
        public string? Dir { get; set; }
        public string? Dist { get; set; }
        public string? Membresia { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using progra.Models;

namespace progra.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Contacto/Index.cshtml
@model progra.Controllers.Contacto
@{
    ViewData["Title"] = "Registro";
}
<h1>Registro</h1>

<form asp-controller="Contacto" asp-action="Registrar" method="post">
    <div class="form-group mb-3">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control" required />
    </div>

   <div class="form-group mb-3">
        <label asp-for="Edad"></label>
        <input asp-for="Edad" type="number" class="form-control" required />
    </div>

    <div class="form-group mb-3">
        <label>Género</label><br />
        <div class="form-check form-check-inline">
            <input asp-for="Genero" type="radio" id="Masculino" class="form-check-input" value="Masculino" />
            <label class="form-check-label" for="Masculino">Masculino</label>
        </div>
        <div class="form-check form-check-inline">
            <input asp-for="Genero" id="Femenino" type="radio" class="form-check-input" value="Femenino" />
            <label class="form-check-label" for="Femenino">Femenino</label>
        </div>
    </div>

     <div class="form-group mb-3">
        <label asp-for="Fecha"></label>
        <input asp-for="Fecha" type="date" class="form-control" required />
    </div>

     <div class="form-group mb-3">
        <label asp-for="Dir"></label>
        <input asp-for="Dir" type="text" class="form-control" required />
    </div>

     <div class="form-group mb-3">
        <label asp-for="Dist"></label>
        <select asp-for="Dist" class="form-control" required>
            <option value="Miraflores">Miraflores</option>
            <option value="San Borja">San Borja</option>
            <option value="La Molina">La Molina</option>
            <option value="Lima">Lima</option>
        </select>
    </div>

     <div class="form-group mb-3">
        <label>Membresía</label><br />
        <div class="form-check form-check-inline">
            <input asp-for="Membresia" id="Basica" type="radio" class="form-check-input" value="Básico" />
            <label class="form-check-label" for="Basica">Básica (500)</label>
        </div>
        <div class="form-check form-check-inline">
            <input asp-for="Membresia" type="radio" id="Premium" class="form-check-input" value="Premium" />
            <label class="form-check-label" for="Premium">Premium (1000)</label>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>

</form>

<h1>@ViewData["MsgRpta"]</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<article>
    <h2>Bella</h2>
    <img src="https://static.fundacion-affinity.org/cdn/farfuture/PVbbIC-0M9y4fPbbCsdvAD8bcjjtbFc0NSP3lRwlWcE/mtime:1643275542/sites/default/files/los-10-sonidos-principales-del-perro.jpg" alt="Foto del viaje con mi mascota" style="width:300px;height:auto;">
    <p>Bella es una Golden Retriever de seis años, conocida por su naturaleza amigable y su pelaje dorado y brillante que siempre parece estar en perfecto estado. Su personalidad radiante y juguetona la convierte en el centro de atención en cualquier lugar al que vaya. Bella tiene una forma especial de alegrar los días de todos a su alrededor con su entusiasmo inagotable y su amor incondicional. Es una mascota increíblemente leal y cariñosa, siempre dispuesta a recibir y ofrecer afecto. Sus travesuras y su energía contagiosa llenan la casa de alegría y risas, haciendo que cada día con ella sea una experiencia llena de amor y diversión.</p>
</article>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - progra</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/progra.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">progra</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Registro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - progra - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>